# .github/workflows/deploy.yml
name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Ensure directory exists
            mkdir -p /var/www/apps/positivus

            # Remove everything including hidden files
            cd /var/www/apps/positivus
            rm -rf .* * || true

            # Clone fresh copy
            git clone https://github.com/ipyatikhatko/positivus-landing-template.git .

            # Build and run Docker
            docker stop positivus || true
            docker rm positivus || true
            docker build -t positivus .
            docker run -d --name positivus --restart unless-stopped -p 8080:80 positivus
